# Generated on 2016-06-17 20:42:22
source("/share/PI/manishad/PCORI/lib/prioritySwitch.R")
.sbatch_paths <- c(
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0001_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0002_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0003_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0004_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0005_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0006_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0007_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0008_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0009_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0010_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0011_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0012_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0013_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0014_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0015_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0016_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0017_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0018_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0019_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0020_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0021_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0022_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0023_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0024_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0025_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0026_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0027_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0028_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0029_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0030_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0031_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0032_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0033_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0034_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0035_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0036_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0037_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0038_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0039_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0040_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0041_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0042_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0043_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0044_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0045_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0046_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0047_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0048_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0049_powerSurv.sbatch",
"/share/PI/manishad/PCORI/power/src/sbatchSurvival/0050_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0051_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0052_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0053_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0054_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0055_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0056_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0057_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0058_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0059_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0060_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0061_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0062_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0063_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0064_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0065_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0066_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0067_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0068_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0069_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0070_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0071_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0072_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0073_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0074_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0075_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0076_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0077_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0078_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0079_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0080_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0081_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0082_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0083_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0084_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0085_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0086_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0087_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0088_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0089_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0090_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0091_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0092_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0093_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0094_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0095_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0096_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0097_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0098_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0099_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0100_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0101_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0102_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0103_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0104_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0105_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0106_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0107_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0108_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0109_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0110_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0111_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0112_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0113_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0114_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0115_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0116_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0117_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0118_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0119_powerSurv.sbatch",
# "/share/PI/manishad/PCORI/power/src/sbatchSurvival/0120_powerSurv.sbatch",
"") 
prioritySwitch(.sbatch_paths)